### ISSUE TITLE
Add actions

### ISSUE THREAD

**Issue by GabrielEValenzuela** [Esc-IngComp-UNC/staff-access-monitoring-system#11]
# Objective
Add automated actions to the repository for continuous integration (CI) to check the following:
1. **Building**: Ensure the project builds successfully for ESP32 targets.
2. **Static Analysis**: Run code quality checks using static analysis tools (e.g., clang-tidy, cppcheck).
3. **Coverage**: Generate and enforce test coverage thresholds for unit tests.

## Deliverables
1. **CI Workflow: Build Check**
   - Implement a GitHub Actions workflow to:
     - Build the project for ESP32 hardware using the ESP-IDF framework.
     - Test on multiple configurations (e.g., different board targets if applicable).

2. **CI Workflow: Static Analysis**
   - Run static analysis tools such as `clang-tidy` or `cppcheck` for code quality checks.
   - Fail the workflow if any issues are detected.

3. **CI Workflow: Test Coverage**
   - Use the ESP-IDF Unity testing framework to:
     - Run unit tests on a virtual or physical ESP32 device (using QEMU or hardware-in-the-loop testing).
     - Generate coverage reports for the codebase.
   - Enforce minimum coverage thresholds (e.g., `80%` for statements, branches, and functions).

4. **Documentation**
   - Update the **README.md** to include a section on CI and coverage, with badges (e.g., build status, coverage).
   - Optionally add a **CONTRIBUTING.md** section explaining the CI process and how developers can run these checks locally.

## Suggested Workflow Configuration
Example GitHub Actions workflow file:

```yaml
name: ESP32 CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0

      - name: Install dependencies
        run: idf.py install

      - name: Build project
        run: idf.py build

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0

      - name: Run cppcheck
        run: cppcheck --enable=all --error-exitcode=1 .

      - name: Run clang-tidy
        run: clang-tidy --checks="*" -p build .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0

      - name: Build and test
        run: |
          idf.py build
          idf.py test

      - name: Generate coverage
        run: gcovr --root . --xml coverage.xml --html-details coverage.html
```

## Acceptance Criteria
- **Building**: The CI pipeline builds the project successfully for the ESP32 target without errors.
- **Static Analysis**: The pipeline runs `cppcheck` and/or `clang-tidy`, failing if issues are detected.
- **Coverage**: Test coverage reports are generated and meet the minimum threshold.
- **Documentation**: The repository contains updated information on the CI workflows and badges for build status and test coverage.
